language: node_js
os:
  # - linux
  - osx
  # - windows
node_js:
  - "14"
before_install:
  # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt -y install libvips-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install vips; fi
install:
  - npm install
before_script:
  - npm run build
after_success:
  - npm run coveralls
